---
ID: "a572bc08-6bad-41c2-a166-775f62f09665"
Parent: "e4a617c0-d4d1-41d2-8d10-fc648d2dfefe"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/CoreySmith/SxaRocks/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181121T193358Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
